
services:
  web:
    image: yiisoftware/yii2-php:8.2-apache

    container_name: yii2-web
    ports:
      - "8080:80"
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: yii2-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: yii2db
      MYSQL_USER: yii2user
      MYSQL_PASSWORD: yii2pass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
